### ISSUE TITLE
How to get extrinsics from E57

### ISSUE THREAD

**Issue by sebdi** [madduci/PCD-E57#1]
Hey,
I have a E57 file which contains several single scans. I'm able to extract each single scan from the E57 file by changing [this line in the code](https://github.com/madduci/PCD-E57/blob/fd5588755f46a6e72a61ff7c8a5b868cae642e55/e57.h#L116), but I need the extrinsic coordinates of the single scans to merge the scans into a global one. Can anyone give me a hint how I extract the extrinsics from the E57 file.

**Comment by madduci** [comment]
Hi

thank you for your feedback. Unfortunately, libE57 itself has a limited capability in this direction, it's not possible to extract extrinsic coordinates of the single scans, it assumes they are already registered in the same coordinate system (please refer to [this page](http://libe57.org/features.html)).
