### ISSUE TITLE
no instructions

### ISSUE THREAD

**Issue by garethByers** [madduci/PCD-E57#10]
I was just wondering how the tool is meant to be setup as there is no instruction on the github page, I would like to use this tool to build an e57 point cloud file from scans collected in a Gazebo simulation and any tips / advice would be welcomed.

**Comment by madduci** [comment]
Hi

Thanks for the interest.
You should have a working installation of the PCL library (follow the
instructions on their website) and then compile this project using the
CMakeLists provided in this repository.

The project is a CLI application which the converts E57 <> PCD files.

Il ven 13 mag 2022, 17:28 garethByers ***@***.***> ha scritto:

**Comment by garethByers** [comment]
So it does not need to go anywhere specific within the PCL library? sorry I am new to this

**Comment by madduci** [comment]
Not really. But without the installed PCL Library on your machine, you
can't build this project.

Il ven 13 mag 2022, 17:39 garethByers ***@***.***> ha scritto:

**Comment by garethByers** [comment]
I have built the project, is there a man page for the commands I do for the conversions? sorry for all the questions and I really appreciate your timely response :)

**Comment by madduci** [comment]
No unfortunately there isn't any man page.

But it provides an help message for the usage

**Comment by garethByers** [comment]
this is the output I got, I have run this for the second time as I cleared the terminal after the first 


gareth@ubuntu:~/Documents$ cmake PCD-E57/
-- -------------------------------------------------------------------------------
-- INSTALL PATH
-- -------------------------------------------------------------------------------
-- CMAKE_INSTALL_PREFIX: /home/gareth/Documents/PCD-E57/install
-- CMAKE_INSTALL_RPATH: /home/gareth/Documents/PCD-E57/install/lib
-- -------------------------------------------------------------------------------
-- Looking for Dependencies
-- -------------------------------------------------------------------------------
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib/x86_64-linux-gnu/libicuuc.so
-- Xerces Library (include: debug;/usr/lib/x86_64-linux-gnu/libxerces-c.so;optimized;/usr/lib/x86_64-linux-gnu/libxerces-c.so)
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib/x86_64-linux-gnu/libicuuc.so
-- Eigen found (include: /usr/include/eigen3, version: 3.3.7)
-- The imported target "vtkParseOGLExt" references the file
   "/usr/bin/vtkParseOGLExt-7.1"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
-- QHULL found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libqhull.so;debug;/usr/lib/x86_64-linux-gnu/libqhull.so)
-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- looking for PCL_COMMON
-- looking for PCL_KDTREE
-- looking for PCL_OCTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_2D
-- looking for PCL_GEOMETRY
-- looking for PCL_IO
-- looking for PCL_FEATURES
-- looking for PCL_ML
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_SURFACE
-- looking for PCL_REGISTRATION
-- looking for PCL_KEYPOINTS
-- looking for PCL_TRACKING
-- looking for PCL_RECOGNITION
-- looking for PCL_STEREO
-- looking for PCL_APPS
-- looking for PCL_IN_HAND_SCANNER
-- looking for PCL_POINT_CLOUD_EDITOR
-- looking for PCL_OUTOFCORE
-- looking for PCL_PEOPLE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gareth/Documents/PCD-E57
gareth@ubuntu:~/Documents$

**Comment by madduci** [comment]
Ok now you have to build the project with "make" to obtain the built
application executable
