### ISSUE TITLE
FOSS Licencing

### ISSUE THREAD

**Issue by jameswhennessey** [madduci/PCD-E57#5]
Hi, 

Thanks for authoring a very useful library. Is there any chance you could put a FOSS license on the project? Without a license it is by default copyrighted and not legally usable in downstream projects.

Thanks!

**Comment by madduci** [comment]
Hi, 
sure, it is a very old project and I didn't put a license back then, I will add a new one soon, thanks for reporting it

**Comment by madduci** [comment]
I've added the MIT License, see [commit 98b6f72e1fe5](https://github.com/madduci/PCD-E57/commit/98b6f72e1fe5b7a2e5cc9181b3187195bf100de1)

**Comment by jameswhennessey** [comment]
Great - thanks!
