### ISSUE TITLE
Cmake compilation error:   Please set the XERCES_ROOT variable to the Xerces directory.

### ISSUE THREAD

**Issue by hedaniel7** [madduci/PCD-E57#7]
Hello there! 

git clone https://github.com/madduci/PCD-E57 && cd PCD-E57 && cmake .

gives me this cmake error:

`-- -------------------------------------------------------------------------------
-- INSTALL PATH
-- -------------------------------------------------------------------------------
-- CMAKE_INSTALL_PREFIX: /home/daniel/Documents/PCD-E57/install
-- CMAKE_INSTALL_RPATH: /home/daniel/Documents/PCD-E57/install/lib
-- -------------------------------------------------------------------------------
-- Looking for Dependencies
-- -------------------------------------------------------------------------------
-- Unable to find Xerces: 
Please set the XERCES_ROOT variable to the Xerces directory.
 (missing: Xerces_INCLUDE_DIR Xerces_LIBRARY_DEBUG Xerces_LIBRARY_RELEASE Xerces_LIBRARY) 
-- Found ICU header files in /usr/include
-- Found ICU libraries: /usr/lib/x86_64-linux-gnu/libicuuc.so
CMake Error at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Unable to find Xerces:

  Please set the XERCES_ROOT variable to the Xerces directory.

   (missing: Xerces_INCLUDE_DIR Xerces_LIBRARY_DEBUG Xerces_LIBRARY_RELEASE Xerces_LIBRARY) 
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindXerces.cmake:75 (find_package_handle_standard_args)
  CMakeLists.txt:66 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/daniel/Documents/PCD-E57/CMakeFiles/CMakeOutput.log".
`

and I do think I have xerces installed:

`sudo apt install libxerces-c3.2
[sudo] password for daniel: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxerces-c3.2 is already the newest version (3.2.0+debian-2).

and apt list | grep xerces gives:

libxerces-c-dev/bionic 3.2.0+debian-2 amd64
libxerces-c-doc/bionic,bionic 3.2.0+debian-2 all
libxerces-c-samples/bionic 3.2.0+debian-2 amd64
libxerces-c3.2/bionic,now 3.2.0+debian-2 amd64 [installed]
libxerces2-java/bionic,bionic 2.11.0-8 all
libxerces2-java-doc/bionic,bionic 2.11.0-8 all`

**Comment by madduci** [comment]
Hi

thanks for the issue. I guess it happens because CMake has updated internally its modules and last time I've checked it with an older version (~3.10), it was working fine.

Can you try to compile xerces from sources and then set the XERCES_ROOT to the folder where your files are compiled and installed?

**Comment by hedaniel7** [comment]
Hi,

I found the solution.

The same error occured when I used cmake 3.10 so it wasn't cmake's fault.

You just need to install xerces this way:

`sudo apt-get update -y`
`sudo apt-get install -y libxerces-c-dev`

and the error disappeared.
