### ISSUE TITLE
Question: What dpes "Got an e57 exception: element value out of min/max bounds" mean?

### ISSUE THREAD

**Issue by hedaniel7** [madduci/PCD-E57#8]
Hello there! I used the following commmand and got the following error:

`./e57_2_pcd ../../Desktop/scans_Scan_022.e57 `
../../Desktop/scans_Scan_022.e57
0
0 0 325.835 -0.0120754 -0.000224117 0.916299 0.400313
Points: 28113609
Scan-0-0.pcd
Values found: 
0Max Value: 3.90817 Min Value: -8.38476
1Max Value: 6.16487 Min Value: -2.45601
2Max Value: 7.51402 Min Value: -4.40356
Number of point to write: 28113609
Source Buffers prepared
**** Got an e57 exception: element value out of min/max bounds (E57_ERROR_VALUE_OUT_OF_BOUNDS)
  Debug info: 
    context: nextInt64=2 minimum=0
    sourceFunctionName: processRecords
    reportingFunctionName: saveE57File
/home/daniel/Documents/PCD-E57/E57/E57FoundationImpl.cpp(8286) : error C35:  <--- occurred on
/home/daniel/Documents/PCD-E57/e57.h(392) : error C0:  <--- reported on
********************* CONVERSION COMPLETED *********************
File: 	../../Desktop/scans_Scan_022.e57
Cloud Size: 	28113609
File Saved: 	Scan-0-0.pcd
********************* CONVERSION COMPLETED *********************
Conversion completed

What does this error mean and why is it possible that it appeared on my dataset? Have I successfully converted my dataset or is there now a mistake in there?

**Comment by madduci** [comment]
Hi
I guess your file has some invalid scaled values or erroneous type of values (e.g. Integer instead of Float), thus producing this error. 
That's a core libE57 error, so maybe your file isn't proper valid?

**Comment by hedaniel7** [comment]
Hi
Thank you for that fast reply.
